version: '2.0'

services:
    http:
      container_name: "http"
      hostname: "http"
      image: httpd:latest
      restart: always
      ports:
        - '80:80'
      volumes:
        - /home/anhanguera/scm-prointer/app:/usr/local/apache2/htdocs
